version: '3.5'

services:
  truffle:
    build: truffle
    container_name: truffle
    hostname: truffle
    environment:
      TZ: Asia/Tokyo
    working_dir: /app
    volumes:
      - ./src:/app:cached
    tty: true
    depends_on:
      - ganache
      - loom
    ports:
      - 3000:3000
      - 3001:3001
  ganache:
    build: ganache
    container_name: ganache
    hostname: ganache
    restart: always
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8545:8545
    volumes:
      - ./ganache/ganache-data:/var/ganache
  loom:
    build: loom
    container_name: loom
    hostname: loom
    restart: always
    environment:
      TZ: Asia/Tokyo
    tty: true
    ports:
      - 46657:46657
      - 8080:8080
    volumes:
      - ./loom/chaindata:/home/node/chaindata
      - ./loom/genesis.json:/home/node/genesis.json
